version: 0.2

phases:

  runtime-versions:
    nodejs: 14
    java: corretto17  
  commands:
    - echo "Installing NPM dependencies..."
    - npm install
    - echo "Instalando OWASP Dependency-Check..."
    - curl -sLO https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.9/dependency-check-9.0.9-release.zip
    - yum install -y unzip || apt-get install -y unzip
    - unzip dependency-check-9.0.9-release.zip
    - echo "Verificando diretórios extraídos..."
    - ls -R  
    - DEPENDENCY_CHECK_DIR=$(find . -type d -name "dependency-check*" | head -n 1)  
    - echo "Diretório encontrado: $DEPENDENCY_CHECK_DIR"
    - chmod +x $DEPENDENCY_CHECK_DIR/bin/dependency-check.sh
      
  pre_build:
    commands:
      - echo "Pre-build phase"
      
  build:
    commands:
      - echo "Build phase"
      - echo "Rodando análise de dependências..."
      - dependency-check/dependency-check/bin/dependency-check.sh --project "meu-projeto" --scan . --format HTML --out reports/

  post_build:
    commands:
      - echo "Análise concluída! Salvando resultados..."
      - aws s3 cp reports/ s3://pipeline5-trabalho-d --recursive  

artifacts:
  files:
    - '**/*'  # Inclui todos os arquivos e subpastas recursivamente
