version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  
    commands:
      - echo Installing NPM dependencies...
      - npm install

  pre_build:
    commands:
      - echo Pre-build phase
      - echo "Baixando e Instalando OWASP Dependency-Check..."
      - curl -s -L https://github.com/jeremylong/DependencyCheck/releases/download/v8.2.1/dependency-check-8.2.1-release.zip -o dependency-check.zip
      - unzip dependency-check.zip -d dependency-check
      - chmod +x dependency-check/bin/dependency-check.sh

  build:
    commands:
      - echo Running OWASP Dependency-Check...
      - /usr/local/bin/dependency-check/dependency-check.sh --project "MeuProjeto" --scan . --format HTML --out reports/
      - echo Build phase
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Checking OWASP Dependency-Check results...
      - cat reports/dependency-check-report.html || echo "Failed to generate dependency check report"

artifacts:
  files:
    - '**/*'  # Inclui todos os arquivos e subpastas recursivamente
